name: cgpa_calculator

description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3
  printing: ^5.14.2
  dio: ^5.4.0
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # 👈 Add this line

flutter_icons:  # 👈 Add this block
  android: true
  ios: true
  image_path: "assets/icon/cgpaIcon3C.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
